### ISSUE TITLE
Stale link: Packaging > Articles > Good Style in modern Emacs Packages

### ISSUE THREAD

**Issue by NickSeagull** [alphapapa/emacs-package-dev-handbook#17]
First, thanks a lot for this repo! Its **extremely** useful 🙏 

Just a heads up: http://ruzkuku.com/texts/emacs-style.html gives a 404 to me

**Comment by alphapapa** [comment]
Thanks.  I wonder what happened to that site.  Is it on the Internet Archive?

**Comment by NickSeagull** [comment]
Looks like so: https://web.archive.org/web/20211103120130/https://ruzkuku.com/texts/emacs-style.html

**Comment by alphapapa** [comment]
Oh, right, that's Philip Kaludercic's.  Well, I doubt he just took that content offline; he probably just moved it.  You should be able to find his current web site or ask him about it (he's active on r/emacs, emacs-devel, etc).

**Comment by 9viz** [comment]
amodernist.com is his new domain.

**Comment by bryce-carson** [comment]
The link now redirects to a malicious website and really should be addressed, @alphapapa.

**Comment by alphapapa** [comment]
> The link now redirects to a malicious website and really should be addressed, @alphapapa.

Ok, can you send a patch?
