### ISSUE TITLE
Add CONTRIBUTE.org?

### ISSUE THREAD

**Issue by casouri** [alphapapa/emacs-package-dev-handbook#2]
Although there is a contribute section, it is more like a todo list. It would be nice if you could provide some guidance on how to contribute.

Some questions in my mind:

1. what is the test branch? 
1. What do you mean by adding thoes blog posts? Do you mean adding a short summary of them? (I made a PR to present my guess)
1. How do I decide what tag to use on my heading?
1. should I run `org-make-toc` when I add a new heading?
1. Are there any conventions that contributors should know?

**Comment by alphapapa** [comment]
1. Looks like I was just testing GitHub readme rendering.
2.  Which blog posts are you referring to?
3.  I've tried to be consistent with the tags I use for similar sections. Look for similar examples in the file, or I can add tags to your additions myself. 
4.  The before-save-hook in the file-local variable should do that automatically.
5.  Yes, there are a few. I should write them down, but in the meantime, just follow the format of the existing sections. You are only the second contributor besides myself, so there hasn't been much need for guidelines yet. 

Thanks!

**Comment by casouri** [comment]
I was referring to [this section](https://github.com/alphapapa/emacs-package-dev-handbook#articles-to-add-013)

I made an example PR: #3

**Comment by alphapapa** [comment]
Those are links to things I want to add to the handbook. Generally I would:

1. Find or make a suitable place in the outline.
2. Add an archive link using the command in the Code section.
3.  Add appropriate tags.
4. Add a short summary.
5. Save and commit.

**Comment by alphapapa** [comment]
I added some guidelines here: https://github.com/alphapapa/emacs-package-dev-handbook#contributions  Please let me know what you think.

**Comment by casouri** [comment]
I think those are good! If you think so you can close the issue.
