### ISSUE TITLE
Mention Eask?

### ISSUE THREAD

**Issue by jcs090218** [alphapapa/emacs-package-dev-handbook#22]
Hi, @alphapapa!

The topic says it all. :) Could you mention [eask](https://github.com/emacs-eask/cli) in the **Tools** section? Maybe somewhere close to [cask](https://github.com/cask/cask)? 🤔

Thank you!

**Comment by alphapapa** [comment]
Hi, sure, done.  :)  Thanks.

**Comment by jcs090218** [comment]
Thank you very much! :D
