### ISSUE TITLE
HTML: separate pages for some of the subheadings?

### ISSUE THREAD

**Issue by casouri** [alphapapa/emacs-package-dev-handbook#5]
The HTML export is pretty cool, it emulates much of the org-mode behaviors.

However, as a reader, I like the Emacs manual's style a bit more. 

For example, each subheading of `* Emacs-lisp` doesn't expand to some other subheadings (which you need to expand again),
but rather jumps to a new page, with all subheadings expanded. Everything you want to know about that topic is there. And there is nothing else. All you do is scrolling and reading.

I think this style is less hacky but more comfortable to read and navigate.

What do you think?

**Comment by alphapapa** [comment]
You might like the org-info.js export style template, which emulates info pages. I thought about using it here, but it has some rough edges and is more complicated and confusing to use.  Maybe we could find a way to export to both styles.

Separate pages is an idea, but it would eliminate some of the benefits of using a single file, like easily generating a table of contents, tag completion, etc.  I don't think it would provide much benefit at this time. 

There's definitely a lot of room for improvement in the export template and CSS.  Feel free to suggest any you come up with.

**Comment by casouri** [comment]
This is just an idea. I'm not up to any CSS theming stuff. I'll leave this issue open for someone might be interested (and work on it).

**Comment by alphapapa** [comment]
I'm going to close this, but feel free to open an issue about CSS stuff if you like.  Thanks.
